# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Shun Yamada
paginate:       5
baseurl:        ""
url:            "https://chesterhow.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Shun Yamada
  url:          http://shunyamada.com
  email:        sy@gociao.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
